allowBuilds:
  esbuild: set this to true or false

shellEmulator: true

trustPolicy: no-downgrade

configDependencies:
  '@thecodeorigin/pnpm-plugin-shared': 1.2.0

onlyBuiltDependencies:
  - esbuild
